### ISSUE TITLE
黑苹果基本上完美~ 谢谢分享！

### ISSUE THREAD

**Issue by fhefh2015** [cc976655/MyBlackAppleEFI#2]
基本上和楼主一样 

使用了楼主的EFI和看了这个教程：https://post.smzdm.com/p/a4wk7e7x/p2/#comments

# 配置如下
| 项目        | 配置   |
| --------   | :-----  |
| CPU         | 英特尔（Intel）i7-8700 | 
|内存         |金士顿骇客神条 16G DDR4 2666 * 2|
| 主板        |   华硕（ASUS）TUF B360M-PLUS GAMING S   | 
| 显卡        |    蓝宝石（SAPPHIRE）RX590 8G 超白金    | 
| 硬盘        |    英特尔760P    | 
|无线网卡|BCM94360CS2 (免驱WIFI和蓝牙) PIC-E三天线|

**Comment by cuiyijiee** [comment]
哈哈，不过我的前几天升级了Catalina ,现在开机后黑屏，还没时间调试是什么原因，QAQ

**Comment by gao03** [comment]
配置差不多，我升级了Catalina，主要功能没啥问题。 @cc976655 
https://github.com/XY-e/HackintoshEFI

**Comment by cuiyijiee** [comment]
> 配置差不多，我升级了Catalina，主要功能没啥问题。 @cc976655
> https://github.com/XY-e/HackintoshEFI

有空我来试一下你这个
