### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Likeyong** [cc976655/MyBlackAppleEFI#4]
我是不是只要把你的 BOOT 和CLOVER 文件夹复制到我的EFI 里面就好了? APPLE/EXTENTIONS 需要处理吗. 感谢

**Comment by cuiyijiee** [comment]
只要BOOT和CLOVER，其他的可以不用处理

**Comment by Likeyong** [comment]
> 只要BOOT和CLOVER，其他的可以不用处理

是安装系统之前替换到U盘里面还是装好系统之后,替换道硬盘里.  我安装失败了经常卡网址

**Comment by cuiyijiee** [comment]
安装之前要放到U盘里面，开机启动用U盘，然后装好了之后可以替换硬盘里面的，这样U盘拔了也就有引导可以启动了。

卡网址是什么情况
