### ISSUE TITLE
双显卡问题

### ISSUE THREAD

**Issue by CChuancey** [cc976655/MyBlackAppleEFI#5]
我和你的主板相同，cpu是i5-9400，显卡Rx580满血版，直接用此EFI安装成功。

下面是我的问题：
BIOS开启核显后，也只有一个独显显示。甚至出现一开始不亮屏，开完机进入桌面才亮屏的情况。

开机第二阶段加载显卡驱动时，屏幕会闪一下

不知道你有没有想让核显和独显一起实现双加速的想法，硬解HEVC啊

已解决，放入最新whatevergreen即可实现双加速

**Comment by CChuancey** [comment]
![image](https://user-images.githubusercontent.com/37216768/71301917-38c06200-23e0-11ea-9a78-525a6451adb4.png)

**Comment by jsrdzhk** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/37216768/71301917-38c06200-23e0-11ea-9a78-525a6451adb4.png)

你好，请问你是按照哪个教程来的，我看的[这个](https://github.com/doesprintfwork/All-in-one-Vanilla-AMD-Hackintosh-Guide)教程，进不去安装界面啊

**Comment by CChuancey** [comment]
想问一下你们这个主板开机亮屏需要几秒，我的按下电源键要8秒左右屏幕才会亮

**Comment by CChuancey** [comment]
我自己装的，只看了这个项目的readme
